# Site settings
title: Evan Jia's CV
description: Evan Jia's CV
favicon: /assets/img/avatar.png
baseurl: /resumecard
url: https://gogoout.github.io/resumecard
rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

gems:
- jekyll-autoprefixer